
2020-12-13 19:08:16,666 INFO: errors [in f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py:541]
2020-12-13 19:08:23,971 ERROR: Exception on /venues/create [POST] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 253, in create_venue_submission
    flash('An error occurred. Venue ' + venues.name + ' could not be listed.')
UnboundLocalError: local variable 'venues' referenced before assignment
2020-12-13 19:08:31,225 ERROR: Exception on /venues/create [POST] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 253, in create_venue_submission
    flash('An error occurred. Venue ' + venues.name + ' could not be listed.')
UnboundLocalError: local variable 'venues' referenced before assignment
2020-12-13 19:09:13,648 INFO: errors [in f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py:541]
2020-12-13 19:10:21,822 ERROR: Exception on /venues/create [POST] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 253, in create_venue_submission
    flash('An error occurred. Venue ' + venues.name + ' could not be listed.')
UnboundLocalError: local variable 'venues' referenced before assignment
2020-12-13 19:10:26,593 ERROR: Exception on /venues/create [POST] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 253, in create_venue_submission
    flash('An error occurred. Venue ' + venues.name + ' could not be listed.')
UnboundLocalError: local variable 'venues' referenced before assignment
2020-12-13 19:10:31,326 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 221, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:11:11,256 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 221, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:11:48,969 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 221, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:14:45,083 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 221, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:14:55,906 INFO: errors [in f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py:541]
2020-12-13 19:27:57,371 INFO: errors [in f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py:540]
2020-12-13 19:28:01,104 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 220, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:28:03,659 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 220, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:30:29,877 INFO: errors [in f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py:540]
2020-12-13 19:30:34,617 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 220, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:30:37,467 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 220, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:33:02,332 INFO: errors [in f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py:541]
2020-12-13 19:33:06,424 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 221, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:33:42,148 INFO: errors [in f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py:541]
2020-12-13 19:33:46,082 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 221, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:35:03,571 INFO: errors [in f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py:540]
2020-12-13 19:35:06,214 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 221, in create_venue_form
    return render_template('forms/new_venue.html', form= VenueForm())
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-12-13 19:35:41,981 INFO: errors [in f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py:540]
2020-12-13 19:35:44,223 ERROR: Exception on /venues/create [GET] [in C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "f:\ABD ALRAHMAN 2020\WorkSpace\Web\FSND-master\projects\01_fyyur\starter_code\app.py", line 220, in create_venue_form
    form = VenueForm()
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "C:\Users\Abdulrahman\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
